/* ========================================================================
 * Copyright 2014 uniandes
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 uniandes

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/
define(['controller/_sportController','delegate/sportDelegate','delegate/loginDelegate'], function() {
    App.Controller.SportController = App.Controller._SportController.extend({
        
//        App.Delegate.LoginDelegate.getLogedUser(function(data) {
//                /*Se crea un div flotante con la libreria js referenciada en el index*/
//                floatingMenu.add('floatdiv',
//                        {
//                            targetRight: 10,
//                            targetTop: 10,
//                            snap: true
//                        });
//                /*con jquery, se agrega el contenido del "user stack" al div flotante creado anteriormente*/
//                $("#floatdiv").html("<table width=\"100%\" height=\"100%\" ><tr><td align=\"center\"><span class=\"glyphicon glyphicon-user\"></span></td><td>" + data + "</td></tr></table>");
//            });


    });
    return App.Controller.SportController;
}); 